// src/config/app.config.ts
// This is the main configuration file for the bot.

// It defines the structure of the configuration and provides a default configuration.
// Please do not edit this file directly unless you know what you're doing.

// TYPE DEFINITIONS
export type Capability = "admin" | "moderator" | "dm" | "member" | "keeper";

export type RoleRef = {
  id?: string;
  name?: string; // we prefer ID, but name is fallback
};

export type CoreRoles = Record<Capability, RoleRef>;

export type GuildChannels = {
  staff: string; // gen staff ops
  resourceTracking?: string;
  rewardsTracking?: string;
  dtpTracking?: string;
  crewCoins?: string;
  magicItems?: string;
  // other generic channels can be added here
};

export type LfgFeatureConfig = {
  enabled: boolean;

  channels: {
    board: string;
    pingForDM?: string;
  };

  roles?: {
    // The base "Future Scheduling LFG" role is self-service (server role menu),
    // so it is intentionally NOT configured here — the bot never touches it.
    dmAvailable?: string;
  };

  tiers: {
    low: string;
    mid: string;
    high: string;
    epic: string;
    pbp: string;
  };
};

export type Features = {
  wipes?: { enabled: boolean }; // placeholder for future wipe tracking feature
  dtp?: { rate: number; max?: number }; // rate: DTP gained per day, max: maximum DTP that can accrue
  lfg?: LfgFeatureConfig;
  // this is where we put other features like charlog and economy.
};

export type GuildConfig = {
  name: string;
  roles: CoreRoles; // map capabilities
  guildMemberRole?: string; // Optional role granted on character initiation
  uninitiatedRole?: string; // Role granted when a player retires their last character
  channels: GuildChannels; // generic channels
  features: Features; // domain-specific knobs
};

export type AppConfig = {
  defaultPrefix: string;
  env: "dev" | "prod" | string;
  guild: {
    id: string;
    config: GuildConfig;
  } | null;
};

// DEFAULT CONFIG
// This is the default config for the bot. This is where you place the roles and channels for your guild.
// No sensitive information goes here, this is just for the bot to know where to operate.
// Sensitive information like tokens and database connection strings go in the .env file.

export const DEFAULT_CONFIG: AppConfig = {
  defaultPrefix: "!",
  env: "dev",
  guild: {
    id: "371668519059980288",
    config: {
      name: "Remnant",
      roles: {
        member: { id: "1333300035596714014" }, // crew
        admin: { id: "371700885014970378" },
        keeper: { id: "1439712101911494827" },
        moderator: { id: "371997814407954434" },
        dm: { id: "1333297187353788437" },
      },
      guildMemberRole: "1360283673903235233",
      uninitiatedRole: "579340109338509356",
      channels: {
        staff: "1401605229996408933",
        resourceTracking: "1347077993830289418",
        rewardsTracking: "1441703165056516137",
        dtpTracking: "1336083139272900740",
        crewCoins: "1457778385710354484",
        magicItems: "1347077949714731048",
      },
      features: {
        wipes: { enabled: false },
        dtp: { rate: 2, max: 365 },
        lfg: {
          enabled: true,
          channels: {
            board: "1406359181702856785",
            pingForDM: "1406359212690243634",
          },
          roles: {
            // base "Future Scheduling LFG" role omitted on purpose (self-service)
            dmAvailable: "1421200706689568860",
          },
          tiers: {
            low: "1421199577981124678",
            mid: "1421199625376895006",
            high: "1421199669903491142",
            epic: "1421199710282190928",
            pbp: "1421207970561392722",
          },
        },
      },
    },
  },
} as const satisfies AppConfig;
